img = imread('data\other_images\onion.png');
M = 4;
act = img;
img = double(img);
figure;imshow(act);title('actual');
res1 = uint8(nn_upsample(img, M));
figure;imshow(res1);title('nn interpolation');
res2 = uint8(linear_upsample(img, M));
figure;imshow(res2);title('linear interpolation');
res3 = uint8(bilinear_upsample(img, M));
figure;imshow(res3);title('bilinear interpolation');
res4 = uint8(bicubic_upsample(img, M));
figure;imshow(res4);title('bicubic interpolation');