img = imread('data/other_images/football.jpg');
M = 6;
act = img;
img = double(imresize(img, 1 / M));
res1 = uint8(nn_upsample(img, M));
res2 = uint8(linear_upsample(img, M));
res3 = uint8(bilinear_upsample(img, M));
res4 = uint8(bicubic_upsample(img, M));
figure;imshow(act);title('actual');
figure;imshow(res1);title('nn interpolation');
figure;imshow(res2);title('linear interpolation');
figure;imshow(res3);title('bilinear interpolation');
figure;imshow(res4);title('bicubic interpolation');