img = imread('data/other_images/pears.png');
ri = img(:, :, 1);
gi = img(:, :, 2);
bi = img(:, :, 3);
n = size(ri, 1);
m = size(ri, 2);
lapf = laplacian_fft(n, m);
res = apply_filter_fft(img, lapf);
res = abs(res);
figure;imshow(uint8(img));title('image');
figure;imshow(uint8(res));title('Laplacian');