img = imread('data/gm1.jpg');
res = uint8(zeros(size(img)));
n = size(img, 1);
m = size(img, 2);
xc = round(n / 2);
yc = round(m / 2);
rmax = sqrt(n*n + m*m) / 4;
p = 1.5;
res1 = apply_spherical_tranform(img(:, :, 1), xc, yc, rmax, p);
res2 = apply_spherical_tranform(img(:, :, 2), xc, yc, rmax, p);
res3 = apply_spherical_tranform(img(:, :, 3), xc, yc, rmax, p);
res(:,:,1) = res1;
res(:,:,2) = res2;
res(:,:,3) = res3;
figure;
title('Original Image');
imshow(img);
figure;
title('changed');
imshow(res);