img = imread('data\stereo1.jpg');
imshow(img);
num_pts = 4;
[inp_x, inp_y] = ginput(num_pts);
img2 = imread('data\stereo2.jpg');
imshow(img2);
[out_x, out_y] = ginput(num_pts);
close all;
out = [out_x'; out_y'];
in = [inp_x'; inp_y'];
mat = homography_matrix(in, out);
res = img;
res1 = apply_transform(img(:, :, 1), mat); 
res2 = apply_transform(img(:, :, 2), mat); 
res3 = apply_transform(img(:, :, 3), mat);
res(:, :, 1) = res1;
res(:, :, 2) = res2;
res(:, :, 3) = res3;
figure;imshow(img);title('input');
figure;imshow(img2);title('target');
figure;imshow(res);title('result');